"""Add registration_link to Event model

Revision ID: 437ae56f47ac
Revises: 
Create Date: 2025-05-07 01:07:34.099027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437ae56f47ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_link', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_events_registration_link', ['registration_link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('uq_events_registration_link', type_='unique')
        batch_op.drop_column('registration_link')
    # ### end Alembic commands ###
